name: Commune
favicon: null
layout_spectrum: 0.25878
typography_spectrum: 0.75875
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141a1a'
    - '#f9f8f4'
    - '#3b382f'
    - '#c7b194'
    - '#7e674f'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.42281338293105364
  rhythmicContrast: 0.75
purpose: []
